on:   
    push:
      branches: [ main ]
      paths:
        - apis/trips/**
name: Deployment trips

jobs:
    build-and-deploy-acr:
        runs-on: ubuntu-latest
        env:
           working-directory: ./apis/trips
           image-name: "devopsoh/api-trips"
           app-name: "openhacklw538em3trips"
        defaults:
            run:
                working-directory: $working-directory
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Build and push image'
          run: az acr build --image "$image-name:${{ github.sha }}" --registry openhacklw538em3acr --file Dockerfile .
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: $app-name
            slot-name: 'staging'
            images: '$image-name:${{ github.sha }}'
