on: [push]
name: Deployment

jobs:
    build-and-deploy-acr:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./apis/poi/web
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Build and push image'
          run: az acr build --image "devopsoh/api-poi:${{ github.sha }}" --registry openhacklw538em3acr --file Dockerfile .
    publish-app-service:
        #needs: build-and-deploy-acr
        runs-on: ubuntu-latest
        steps:
         - name: 'Login via Azure CLI'
           uses: azure/login@v1
           with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}
         - name: Deploy to Azure Web App
           uses: azure/webapps-deploy@v2
           with:
            app-name: 'openhacklw538em3poi'
            slot-name: 'staging'
            images: 'devopsoh/api-poi:85078c120e8b15aced6718da31d23eddb68e9fdc'
