on: [push]
name: Deployment poi

jobs:
    build-and-deploy-acr:
        runs-on: ubuntu-latest
        env:
           working-directory: ./apis/poi/web
           image-name: "devopsoh/api-poi"
           app-name: "openhacklw538em3poi"
        defaults:
            run:
                working-directory: ./apis/poi/web
        steps:
        - name: test
          run: echo $working-directory
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Build and push image'
          run: az acr build --image "$image-name:${{ github.sha }}" --registry openhacklw538em3acr --file Dockerfile .
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: $app-name
            slot-name: 'staging'
            images: '$image-name:${{ github.sha }}'
